name: Test driven ontology development workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install
      - name: Run Ontology Tests
        working-directory: ./tests
        run: |
          make
      - name: Test java
        run: |
          curl -O https://dlcdn.apache.org/jena/binaries/apache-jena-4.4.0.tar.gz
          tar xzf apache-jena-4.4.0.tar.gz
          sh ./.github/validate.sh
